builders:
  assetBuilder:
    import: "package:asset_builder/builder.dart"
    builder_factories: ["assetBuilder"]
    build_extensions: {".dart": ["asset_builder.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]